version:  '3'
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '${PHPMYADMIN_PORT}:80'
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - default

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    restart: on-failure
    working_dir: /app
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    env_file:
      - .env

  nginx:
    image: nginx:${NGINX_VERSION}-alpine
    restart: on-failure
    volumes:
      - './app/public/:/app/public'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - './logs:/var/log/nginx:rw'
    depends_on:
      - php
    ports:
      - '${NGINX_PORT}:80'
